version: '2'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    platform: linux/amd64/v2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kerberos:
    platform: linux/amd64/v2
    image: kerberos:local
    container_name: kerberos
    build:
      context: .
      dockerfile: Dockerfile.kerberos
    environment:
      KRB5_REALM: UNEY.COM
      KDC_RELM: /etc/krb5kdc
    ports:
      - 88:88
      - 749:749
    volumes:
      - ./kerberos/krb5kdc:/var/lib/krb5kdc
      - ./kerberos/keytabs:/var/lib/keytabs
      - ./kerberos/krb5.conf:/etc/krb5.conf
      - ./kerberos/kdc.conf:/etc/krb5kdc/kdc.conf
      - ./kerberos/kdc-start.sh:/usr/local/bin/kdc-start.sh

  kafka:
    image: confluentinc/cp-kafka:latest
    platform: linux/amd64/v2
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
      - kerberos
    volumes:
      - ./kerberos/keytabs:/mnt
      - ./kerberos/krb5.conf:/etc/krb5.conf
      - ./kerberos/krb5-h100.conf:/etc/krb5-h100.conf
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
      - ./kafka_client_jaas.conf:/etc/kafka/kafka_client_jaas.conf
      - ./kafka-client.properties:/etc/kafka/kafka-client.properties
      - ./kafka-h10-client.properties:/etc/kafka/kafka-h10-client.properties
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_SASL_ENABLED_MECHANISMS: GSSAPI
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: GSSAPI
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_LISTENERS: SASL_PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_SASL_KERBEROS_SERVICE_NAME: kafka-broker
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ZOOKEEPER_SASL_ENABLED: "false"
      KAFKA_OPTS: '-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf'
      # -Dsun.security.krb5.debug=true -Dcom.ibm.security.jgss.debug=all -Dcom.ibm.security.krb5.Krb5Debug=all -Dsun.security.jgss.debug=true'